# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [2]:
# import libraries
import numpy as np
import pandas as pd
import re
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [3]:
# import dataset
pokemon = pd.read_csv('pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [4]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [5]:
# your code here

#ds['Type 1'].unique()

poke_types = np.array(pokemon[['Type 1', 'Type 2']])
poke_types

array([['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ...,
       ['Psychic', 'Ghost'],
       ['Psychic', 'Dark'],
       ['Fire', 'Water']], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [6]:
# your code here


# copied from class; Tried to figure out an alternative, but nothing this simple. 
# I Think I understand it and'll be able to use it in the future.
dict_find = {name: re.compile(r'\w*Mega\b').sub('Mega', name) for name in pokemon["Name"]}
pokemon["Name"] = pokemon["Name"].map(dict_find, pokemon["Name"])

In [7]:
pokemon["Name"]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3            Mega Venusaur
4               Charmander
              ...
795                Diancie
796           Mega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion
Name: Name, Length: 800, dtype: object

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [8]:
# your code here
# I rounded it to 2 decimal places to make it more readable, 'though I suspect it might 
# influence future results (will it?). What's the proper/best practice in these situations?
pokemon["A/D Ratio"] = round(pokemon["Attack"] / pokemon["Defense"], 2)

pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.67
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.45
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.83
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.67
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.92

#### Identify the pokemon with the highest `A/D Ratio`.

In [9]:
# your code here

# if by identify you mean present the "A/D Ratio" value AND the pokemon's name
print(pokemon.loc[pokemon["A/D Ratio"] == pokemon["A/D Ratio"].max(), ["Name", "A/D Ratio"]])

print()

# if by identify you mean present ONLY pokemon's name
print(pokemon.loc[pokemon["A/D Ratio"] == pokemon["A/D Ratio"].max(), "Name"].values[0])
#pokemon.describe()
#pokemon

                   Name  A/D Ratio
429  DeoxysAttack Forme        9.0

DeoxysAttack Forme

#### Identify the pokemon with the lowest A/D Ratio.

In [10]:
# your code here

# if by identify you mean present the "A/D Ratio" value AND the pokemon's name
print(pokemon.loc[pokemon["A/D Ratio"] == pokemon["A/D Ratio"].min(), ["Name", "A/D Ratio"]])

        Name  A/D Ratio
230  Shuckle       0.04

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [11]:
# your code here

# Found this idea through Ricardo.
pokemon.loc[pokemon["Type 2"].isnull() == False, "Combo Type"] = pokemon[["Type 1", "Type 2"]].astype(str).apply('-'.join, axis = 1)
pokemon.loc[pokemon["Type 2"].isnull() == True, "Combo Type"] = pokemon["Type 1"]
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.21,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.67,Rock-Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.45,Rock-Fairy
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.83,Psychic-Ghost
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.67,Psychic-Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.92,Fire-Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [12]:
# your code here
top5 = pokemon.sort_values("A/D Ratio", ascending= False)[:5]
top5

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.00,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.50,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.75,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.12,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.00,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [17]:
# your code here

# is this what's being asked?
combo5 = list(top5.groupby("Combo Type").count().index)
combo5

['Bug-Poison', 'Psychic', 'Rock', 'Water-Dark']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [23]:
# your code here
# Rounded to make it more readable. If you comment out the round, you'll find the result to
# be the same.
final = pokemon.groupby("Combo Type").mean().loc[combo5,:]
readable = final.round(2)

In [24]:
readable

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Bug-Poison,199.17,347.92,53.75,68.33,58.08,42.50,59.33,65.92,2.33,0.00,1.32
Psychic,381.97,464.55,72.55,64.95,67.24,98.55,82.39,78.87,3.34,0.24,1.16
Rock,410.11,409.44,67.11,103.33,107.22,40.56,58.33,32.89,3.89,0.11,1.26
Water-Dark,347.67,493.83,69.17,120.00,65.17,88.83,63.50,87.17,3.17,0.00,2.29